-- AlterTable
ALTER TABLE "Leave" ALTER COLUMN "startDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "endDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "dueDate" SET DEFAULT CURRENT_TIMESTAMP;
